In [1]:
import zipfile
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
marathon_df = pd.read_csv("/Users/justinmasters/Documents/DA_prereq_Justin_Masters/Notebooks/Age_and_Endurance/Data/Results.csv")
marathon_df.head()

                Race  Year                Name Gender  Age  Finish Age Bracket
0  Columbus Marathon  2015      Becky Williams      F   29   13645    Under 35
1  Columbus Marathon  2015     Jessica Sheahan      F   27   13648    Under 35
2  Columbus Marathon  2015        Kelsey Stief      F   27   13650    Under 35
3  Columbus Marathon  2015        Mehgan Cline      F   26   13650    Under 35
4  Columbus Marathon  2015  Stefanie Driesenga      F   28   13652    Under 35

In [37]:
marathon_df.tail()

,Race,Year,Name,Gender,Age,Finish,Age Bracket
2053361,Marine Corps Marathon,2019,Daryl Young,M,39,18575,35-39
2053362,Marine Corps Marathon,2019,Ella Biggins,F,24,18575,Under 35
2053363,Marine Corps Marathon,2019,Kevin Klym,M,44,18575,40-44
2053364,Marine Corps Marathon,2019,Casey A Shapiro,F,34,18578,Under 35
2053365,Marine Corps Marathon,2019,Zhaowei Liu,M,64,18578,60-64

In [36]:
marathon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2053366 entries, 0 to 2053365
Data columns (total 7 columns):
 #   Column       Dtype
---  ------       -----
 0   Race         object
 1   Year         int64
 2   Name         object
 3   Gender       object
 4   Age          int64
 5   Finish       int64
 6   Age Bracket  object
dtypes: int64(3), object(4)
memory usage: 109.7+ MB

In [49]:
unique_values = sorted(marathon_df['Age'].unique())
unique_values

[np.int64(-9),
 np.int64(-1),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(70),
 np.int64(71),
 np.int64(72),
 np.int64(73),
 np.int64(74),
 np.int64(75),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(84),
 np.int64(85),
 np.int64(86),
 np.int64(87),
 np.int64(88),
 np.int64(89),
 np.int64(90),
 np.int64(91),
 np.int64(94),
 np.int64(98),
 np.int64(99),
 np.int64(116)]

In [58]:
# narrow dataset down to the marathon incorrect ages

marathon_2019 = marathon_df[(marathon_df['Year'] == 2016)]
marathon_2019.tail()

,Race,Year,Name,Gender,Age,Finish,Age Bracket
2050061,Marine Corps Marathon,2016,Jan Show,F,62,22409,60-64
2050062,Marine Corps Marathon,2016,Crystal Corporal,F,51,22371,50-54
2050063,Marine Corps Marathon,2016,Laurie MacK,F,53,22918,50-54
2050064,Marine Corps Marathon,2016,Thelma Manning,F,37,22555,35-39
2050065,Marine Corps Marathon,2016,Gabrielle Friedman,F,19,21781,Under 35

In [59]:
marathon_2019.to_csv('Finding age')

In [61]:
unique_values = sorted(marathon_2019['Age'].unique())
unique_values

[np.int64(-1),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(70),
 np.int64(71),
 np.int64(72),
 np.int64(73),
 np.int64(74),
 np.int64(75),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(83),
 np.int64(84),
 np.int64(85),
 np.int64(86),
 np.int64(88),
 np.int64(98),
 np.int64(99),
 np.int64(116)]

In [62]:
marathon_20191 = marathon_df[(marathon_df['Age'] == 116)]
marathon_20191.tail()

                       Race  Year       Name Gender  Age  Finish  Age Bracket
233975  Long Beach Marathon  2016  CINDY LAI      F  116   27058  80 and Over

In [66]:
cindy = marathon_2019.iloc[20880]
cindy

Race           Long Beach Marathon
Year                          2016
Name                     CINDY LAI
Gender                           F
Age                            116
Finish                       27058
Age Bracket            80 and Over
Name: 233975, dtype: object